name: HumanOmni
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.0
      - bitsandbytes==0.43.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.18.2
      - distro==1.9.0
      - einops==0.6.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.121.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.34.2
      - imageio-ffmpeg==0.6.0
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.22.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - openai==2.7.2
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - peft==0.11.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pysubs2==1.8.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scenedetect==0.6.3
      - scikit-learn==1.3.0
      - scipy==1.11.4
      - sentry-sdk==2.44.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.49.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.3
      - tokenizers==0.20.3
      - tomli==2.3.0
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.45.0
      - triton==2.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.22.3
      - wcwidth==0.2.14
      - werkzeug==3.1.3
